import { auth, cloudFunctions } from "./firebase.js";
import { beginPortalLoading, endPortalLoading } from "./loading-indicator.js";
import { httpsCallable } from "https://www.gstatic.com/firebasejs/11.6.1/firebase-functions.js";
const callList=httpsCallable(cloudFunctions,"listManagementPortalSharedItems");
const callUrl=httpsCallable(cloudFunctions,"getManagementPortalSharedFileUrl");
const state={folderId:null,rootShareId:null};
const token=()=>auth.currentUser?.getIdToken()||Promise.reject(new Error("Keine aktive Anmeldung gefunden."));
function fmt(v){if(!v)return"–";const d=new Date(v);return Number.isNaN(d.getTime())?"–":d.toLocaleString("de-DE",{dateStyle:"short",timeStyle:"short"});}
function size(n=0){n=Number(n)||0;if(!n)return"0 B";const u=["B","KB","MB","GB"];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return`${n.toFixed(i?1:0)} ${u[i]}`}
function previewable(f){const t=String(f.contentType||"").toLowerCase(),n=String(f.name||"").toLowerCase();return t==="application/pdf"||n.endsWith(".pdf")||t.startsWith("image/")||t.startsWith("text/")||t.startsWith("video/");}
export async function renderSharedFilesModule({content,esc,toast}){
 content.innerHTML=`<div class="info-strip"><strong>Für mich freigegeben:</strong> Hier sehen Sie Ordner, die andere Portalnutzer mit Ihnen oder mit allen Portalnutzern geteilt haben. Die Inhalte sind schreibgeschützt.</div><div class="card"><div id="shared-breadcrumbs" class="myfiles-breadcrumbs" hidden></div><div id="shared-list"><div class="myfiles-empty"><span>♧</span><strong>Freigaben werden geladen …</strong></div></div></div>`;
 const list=content.querySelector('#shared-list'), crumbs=content.querySelector('#shared-breadcrumbs');
 async function load(){const loadingId=beginPortalLoading(state.folderId?"Ordnerinhalt wird geladen …":"Dateien werden geladen …");try{const idToken=await token();const r=(await callList({idToken,folderId:state.folderId,rootShareId:state.rootShareId})).data||{}; draw(r);}catch(e){list.innerHTML=`<div class="myfiles-empty"><span>!</span><strong>Freigaben konnten nicht geladen werden</strong><small>${esc(e.message||'Unbekannter Fehler')}</small></div>`;}finally{endPortalLoading(loadingId);}}
 function draw(r){const roots=r.roots||[],folders=r.folders||[],files=r.files||[]; if(!state.folderId){crumbs.hidden=true;list.innerHTML=roots.length?roots.map(x=>`<div class="myfiles-row folder"><button class="myfiles-name-cell" data-root="${esc(x.id)}"><span class="myfiles-type-icon folder-icon2">▰</span><span><strong>${esc(x.name)}</strong><small>Freigegeben von ${esc(x.ownerName||'Unbekannt')}</small></span></button><div>${fmt(x.updatedAt||x.createdAt)}</div><div>Ordner</div><div class="myfiles-actions"><button class="btn small" data-root="${esc(x.id)}">Öffnen</button></div></div>`).join(''):`<div class="myfiles-empty"><span>♧</span><strong>Noch keine Freigaben</strong><small>Sobald ein anderer Portalnutzer einen Ordner für Sie freigibt, erscheint er hier.</small></div>`;list.querySelectorAll('[data-root]').forEach(b=>b.onclick=()=>{state.folderId=b.dataset.root;state.rootShareId=b.dataset.root;load()});return;}
 crumbs.hidden=false;crumbs.innerHTML=`<button class="myfiles-crumb" data-home>Für mich freigegeben</button>${(r.breadcrumbs||[]).map((b,i)=>`<span>›</span><button class="myfiles-crumb ${i===(r.breadcrumbs||[]).length-1?'active':''}" data-folder="${esc(b.id)}">${esc(b.name)}</button>`).join('')}`;crumbs.querySelector('[data-home]').onclick=()=>{state.folderId=null;state.rootShareId=null;load()};crumbs.querySelectorAll('[data-folder]').forEach(b=>b.onclick=()=>{state.folderId=b.dataset.folder;load()});
 const rows=[...folders.map(x=>`<div class="myfiles-row folder"><button class="myfiles-name-cell" data-folder-open="${esc(x.id)}"><span class="myfiles-type-icon folder-icon2">▰</span><span><strong>${esc(x.name)}</strong><small>Ordner · Eigentümer: ${esc(r.ownerName||'')}</small></span></button><div>${fmt(x.updatedAt||x.createdAt)}</div><div>–</div><div class="myfiles-actions"><button class="btn small" data-folder-open="${esc(x.id)}">Öffnen</button></div></div>`),...files.map(x=>`<div class="myfiles-row file"><button class="myfiles-name-cell" data-file="${esc(x.id)}"><span class="myfiles-type-icon">DOC</span><span><strong>${esc(x.name)}</strong><small>${esc(x.contentType||'Datei')} · Eigentümer: ${esc(r.ownerName||'')}</small></span></button><div>${fmt(x.updatedAt||x.createdAt)}</div><div>${size(x.size)}</div><div class="myfiles-actions"><button class="btn small" data-file="${esc(x.id)}">${previewable(x)?'Öffnen':'Herunterladen'}</button></div></div>` )];list.innerHTML=rows.length?rows.join(''):`<div class="myfiles-empty"><span>▱</span><strong>Dieser freigegebene Ordner ist leer</strong></div>`;list.querySelectorAll('[data-folder-open]').forEach(b=>b.onclick=()=>{state.folderId=b.dataset.folderOpen;load()});list.querySelectorAll('[data-file]').forEach(b=>b.onclick=async()=>{try{const idToken=await token();const rr=(await callUrl({idToken,fileId:b.dataset.file,rootShareId:state.rootShareId,mode:previewable(files.find(x=>x.id===b.dataset.file))?'inline':'attachment'})).data;window.open(rr.url,'_blank','noopener')}catch(e){toast(e.message||'Datei konnte nicht geöffnet werden.')}});}
 await load();
}
